@startuml ecommerce
class DefaultEntity{
- id : Long
- dataCriacao : LocalDateTime
- version : Integer

}

class Panela{
- modelo : String
- preco : double
- peso : double
- capacidadeLitros : double
- descricao : String
- isInducao : boolean
}

class Colecao{
- nome : String
}

class Categoria{
- tipo : String
}

class Cor{
- nome : String
}

abstract Componente{
- peso : double
}

enum Tamanho{
+ PEQUENA
+ MEDIA
+ GRANDE
+ GIGANTE
}

enum TipoSustentacao{
+ CABO
+ ALCA
}
class Fornecedor{
- nome : String
- telefone : String
- cnpj : String
}

class Material{
- nome : String
- qualidades[] : String
}

class Tampa{
- isDePressao : boolean
}

class Fundo{
- espessura : double
- isAntiaderente : boolean
}

class Sustentacao{
- tamanhoEmCm : int
- quantidade : int
}

class Usuario{
- nome : String
- sobrenome : String
- login : String
- senha : String
}

enum Perfil{
+ ADMIN
+ FUCIONARIO
+ CLIENTE
}

class Endereco{
- rua : String
- numero : String
- cidade : String
- estado : String
- cep : String
}

class ListaDeDesejo{
}

class Pedido{
- valorBruto : double
- valorDesconto : double
}

class ItemPedido{
- quantidade : Integer
- valorUnitario : double
}

enum StatusPedido{
+ CANCELADO
+ PENDENTE
+ ENTREGUE
}

class CupomDesconto {
- codigo : String
- percentualDesconto : double
- valorDesconto : double
- dataValidade : LocalDateTime
- quantidadeDisponivel : int
- isAtivo : boolean
}

abstract Pagamento{
- dataProcessado : LocalDateTime
}

class CartaoCredito{
- numero : String
- nomeTitular : String
- dataValidade : String
- codigoSeguranca : String
}

class CartaoDebito{
- numero : String
- nomeTitular : String
- dataValidade : String
- codigoSeguranca : String
}

class Pix{
- chavePix : String
}

class Boleto{
- codigoBarras : String
}

enum TipoPagamento{
+ CARTAO_CREDITO
+ CARTAO_DEBITO
+ BOLETO
+ PIX
}

enum StatusPagamento{
+ PENDENTE
+ APROVADO
+ RECUSADO
}


Panela "*" o--> "1" Colecao
Panela "1" *--> "1" Fundo
Panela "1" *--> "1" Sustentacao
Panela "1" *--> "0..1" Tampa
Panela "*" o--> "1" Fornecedor
Panela "*" *--> "1" Tamanho
Panela "*" o--> "1" Categoria
Panela "*" o--> "1" Cor
Panela "*" o--> "1" Material
Panela <-up- ItemPedido

Componente <|-up- Tampa
Componente <|-up- Fundo
Componente <|-up- Sustentacao
Componente "*" o-up- "*" Material

Sustentacao "*" -down-> "1" TipoSustentacao

Usuario "*" --> "1" Perfil
Usuario "*" --> "1" Endereco

ListaDeDesejo "1" --> "1" Usuario
ListaDeDesejo "*" --> "*" Panela

Pedido "*" --> "1" Usuario
Pedido "1" --> "*" ItemPedido
Pedido "*" --> "1" StatusPedido
Pedido "1" --> "1" Pagamento
Pedido "*" --> "0..1" CupomDesconto
Pedido -- TipoPagamento

Pagamento "*" --> "1" StatusPagamento
Pagamento <|-- CartaoCredito
Pagamento <|-- CartaoDebito
Pagamento <|-- Pix
Pagamento <|-- Boleto

@enduml